---
galaxy_info:
  author: Sébastien Han
  description: Handles ceph-ansible default vars for all roles
  license: Apache
  min_ansible_version: 1.7
  platforms:
    - name: Ubuntu
      versions:
        - trusty
  categories:
    - system
dependencies: []
