---
- include: check_mandatory_vars.yml

- include: pre_requisite.yml
  when: not containerized_deployment
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- include: ./scenarios/journal_collocation.yml
  when:
    - (journal_collocation or dmcrypt_journal_collocation)
    - not containerized_deployment
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- include: ./scenarios/raw_multi_journal.yml
  when:
    - raw_multi_journal
    - not containerized_deployment
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- include: ./scenarios/dmcrypt-dedicated-journal.yml
  when:
    - dmcrypt_dedicated_journal
    - not containerized_deployment
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- name: create lvm osds with ceph-volume
  include: ./scenarios/lvm.yml
  when:
    - lvm_osds
    - not containerized_deployment
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- name: ensure osd daemons are started
  include: start_osds.yml
  when:
    - not containerized_deployment
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- include: ./docker/main.yml
  when: containerized_deployment
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False
