---
galaxy_info:
  author: Daniel Gryniewicz
  description: Installs Ceph NFS Gateway
  license: Apache
  min_ansible_version: 1.7
  platforms:
    - name: Ubuntu
      versions:
        - trusty
  categories:
    - system
dependencies:
  - { role: ceph.ceph-common }
